apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-vault-generator
  namespace: password-vault-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-vault-generator
  template:
    metadata:
      labels:
        app: password-vault-generator
    spec:
      containers:
      - name: password-vault-generator
        image: ghcr.io/keithhubner/passwordvaultgenerator:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nextjs-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
        - name:  ghcr-secret