export const commonWeakPasswords = [
  "password",
  "123456",
  "qwerty",
  "abc123",
  "letmein",
  "monkey",
  "welcome",
  "admin",
  "dragon",
  "sunshine",
  "princess",
  "football",
  "baseball",
  "master",
  "shadow",
  "superman",
  "trustno1",
  "iloveyou",
  "passw0rd",
  "p@ssw0rd",
  "welcome1",
  "Password1",
  "qwerty123",
  "123qwe",
  "1q2w3e",
  "asdf1234",
  "zxcvbn",
  "password123",
  "12345678",
  "111111",
  "1234567890",
]

export const popularWebsites = [
  "google.com",
  "facebook.com",
  "amazon.com",
  "twitter.com",
  "instagram.com",
  "linkedin.com",
  "netflix.com",
  "microsoft.com",
  "apple.com",
  "github.com",
  "youtube.com",
  "reddit.com",
  "wikipedia.org",
  "yahoo.com",
  "twitch.tv",
]

export const businessDepartments = [
  "Executive",
  "Finance",
  "Human Resources",
  "Information Technology",
  "Marketing",
  "Operations",
  "Research & Development",
  "Sales",
  "Customer Support",
  "Legal",
  "Procurement",
  "Quality Assurance",
  "Product Management",
  "Business Development",
  "Public Relations",
  "Customer Success",
  "Administration",
  "Facilities",
  "Security",
  "Engineering",
]

export const businessFunctions = [
  "Strategy",
  "Analytics",
  "Compliance",
  "Risk Management",
  "Training",
  "Innovation",
  "Digital Transformation",
  "Corporate Communications",
  "Investor Relations",
  "Supply Chain",
  "Logistics",
  "Manufacturing",
  "Design",
  "User Experience",
  "Data Science",
  "Artificial Intelligence",
  "Cloud Infrastructure",
  "Mobile Development",
  "Web Development",
  "DevOps",
  "Customer Experience",
  "Brand Management",
  "Social Media",
  "Content Creation",
  "Events",
  "Partnerships",
  "Mergers & Acquisitions",
  "Accounting",
  "Payroll",
  "Benefits",
  "Recruitment",
  "Talent Development",
  "Internal Communications",
  "Corporate Social Responsibility",
  "Sustainability",
]

export const businessRegions = [
  "North America",
  "South America",
  "Europe",
  "Asia Pacific",
  "Middle East",
  "Africa",
  "Global",
  "Eastern",
  "Western",
  "Northern",
  "Southern",
  "Central",
]