export const commonWeakPasswords = [
  "password",
  "123456",
  "qwerty",
  "abc123",
  "letmein",
  "monkey",
  "welcome",
  "admin",
  "dragon",
  "sunshine",
  "princess",
  "football",
  "baseball",
  "master",
  "shadow",
  "superman",
  "trustno1",
  "iloveyou",
  "passw0rd",
  "p@ssw0rd",
  "welcome1",
  "Password1",
  "qwerty123",
  "123qwe",
  "1q2w3e",
  "asdf1234",
  "zxcvbn",
  "password123",
  "12345678",
  "111111",
  "1234567890",
]

export const popularWebsites = [
  "google.com",
  "facebook.com",
  "amazon.com",
  "twitter.com",
  "instagram.com",
  "linkedin.com",
  "netflix.com",
  "microsoft.com",
  "apple.com",
  "github.com",
  "youtube.com",
  "reddit.com",
  "wikipedia.org",
  "yahoo.com",
  "twitch.tv",
]

// Enterprise URLs organized by category
export const defaultEnterpriseUrlsByCategory: Record<string, string[]> = {
  "CRM & Sales": [
    "salesforce.com",
    "dynamics.microsoft.com",
    "hubspot.com",
    "zoho.com",
  ],
  "Security & SIEM": [
    "splunk.com",
    "qradar.cloud.ibm.com",
    "sentinel.microsoft.com",
    "elastic.co",
    "sumologic.com",
    "datadog.com",
    "newrelic.com",
    "paloaltonetworks.com",
    "crowdstrike.com",
    "okta.com",
    "onelogin.com",
    "duo.com",
  ],
  "Enterprise Collaboration": [
    "slack.com",
    "teams.microsoft.com",
    "zoom.us",
    "webex.com",
    "workday.com",
    "oracle.com",
    "sap.com",
  ],
  "Cloud Infrastructure": [
    "aws.amazon.com",
    "console.cloud.google.com",
    "portal.azure.com",
    "cloud.ibm.com",
  ],
  "DevOps & CI/CD": [
    "jenkins.io",
    "gitlab.com",
    "bitbucket.org",
    "circleci.com",
    "travis-ci.com",
    "jfrog.com",
    "sonarqube.org",
  ],
  "Project Management": [
    "jira.atlassian.com",
    "confluence.atlassian.com",
    "monday.com",
    "asana.com",
    "servicenow.com",
    "smartsheet.com",
  ],
  "Analytics & BI": [
    "tableau.com",
    "powerbi.microsoft.com",
    "looker.com",
    "qlik.com",
    "thoughtspot.com",
  ],
  "HR & Talent": [
    "adp.com",
    "greenhouse.io",
    "lever.co",
    "bamboohr.com",
    "ultipro.com",
  ],
  "Finance & ERP": [
    "netsuite.com",
    "concur.com",
    "expensify.com",
    "coupa.com",
  ],
  "Document Management": [
    "box.com",
    "dropbox.com",
    "sharepoint.com",
    "documentum.com",
  ],
  "Marketing Automation": [
    "marketo.com",
    "eloqua.com",
    "pardot.com",
    "mailchimp.com",
  ],
  "IT Service Management": [
    "pagerduty.com",
    "statuspage.io",
    "freshservice.com",
    "zendesk.com",
  ],
}

// Flat array for backward compatibility with generators
export const enterpriseWebsites = Object.values(defaultEnterpriseUrlsByCategory).flat()

export const businessDepartments = [
  "Executive",
  "Finance",
  "Human Resources",
  "Information Technology",
  "Marketing",
  "Operations",
  "Research & Development",
  "Sales",
  "Customer Support",
  "Legal",
  "Procurement",
  "Quality Assurance",
  "Product Management",
  "Business Development",
  "Public Relations",
  "Customer Success",
  "Administration",
  "Facilities",
  "Security",
  "Engineering",
]

export const businessFunctions = [
  "Strategy",
  "Analytics",
  "Compliance",
  "Risk Management",
  "Training",
  "Innovation",
  "Digital Transformation",
  "Corporate Communications",
  "Investor Relations",
  "Supply Chain",
  "Logistics",
  "Manufacturing",
  "Design",
  "User Experience",
  "Data Science",
  "Artificial Intelligence",
  "Cloud Infrastructure",
  "Mobile Development",
  "Web Development",
  "DevOps",
  "Customer Experience",
  "Brand Management",
  "Social Media",
  "Content Creation",
  "Events",
  "Partnerships",
  "Mergers & Acquisitions",
  "Accounting",
  "Payroll",
  "Benefits",
  "Recruitment",
  "Talent Development",
  "Internal Communications",
  "Corporate Social Responsibility",
  "Sustainability",
]

export const businessRegions = [
  "North America",
  "South America",
  "Europe",
  "Asia Pacific",
  "Middle East",
  "Africa",
  "Global",
  "Eastern",
  "Western",
  "Northern",
  "Southern",
  "Central",
]
